#!/usr/bin/env bash
# Sync the portfolio table data with supabase/personal-seed.sql.
#   ./scripts/personal-seed.sh pull  # database -> file
#   ./scripts/personal-seed.sh push  # file -> database
# Reads SUPABASE_DB_URL from .env (see .env.example).
# Runs psql/pg_dump via docker, so no local Postgres install is needed.
set -euo pipefail
cd "$(dirname "$0")/.."

SEED_FILE=supabase/personal-seed.sql
PG_IMAGE=postgres:17-alpine
[[ -f .env ]] && source .env
: "${SUPABASE_DB_URL:?Set SUPABASE_DB_URL in .env or the environment}"

case "${1:-}" in
  pull)
    {
      echo "-- Personal portfolio data. Generated by scripts/personal-seed.sh pull; apply with push."
      echo "TRUNCATE public.portfolio, public.portfolio_v2;"
      docker run --rm --network host "$PG_IMAGE" pg_dump "$SUPABASE_DB_URL" --data-only --column-inserts \
        -t public.portfolio -t public.portfolio_v2
    } > "$SEED_FILE"
    echo "Wrote $SEED_FILE"
    ;;
  push)
    docker run --rm -i --network host "$PG_IMAGE" psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 --single-transaction \
      < "$SEED_FILE"
    ;;
  *)
    echo "Usage: $0 {pull|push}" >&2
    exit 1
    ;;
esac
