-- Baseline schema: portfolio tables, trigger function, RLS policies
-- Captured from the existing self-hosted database.

-- Tables -------------------------------------------------------------------

CREATE TABLE public.portfolio (
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public."Portfolio_id_seq"
        START WITH 1 INCREMENT BY 1 CACHE 1
    ) NOT NULL,
    "Projects" jsonb,
    CONSTRAINT "Portfolio_pkey" PRIMARY KEY (id)
);

CREATE TABLE public.portfolio_v2 (
    id bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.portfolio_new_id_seq
        START WITH 1 INCREMENT BY 1 CACHE 1
    ) NOT NULL,
    "Sections" jsonb,
    "Force Update" bigint,
    CONSTRAINT portfolio_new_pkey PRIMARY KEY (id)
);

-- Trigger function ---------------------------------------------------------
-- Broadcasts row changes over Realtime. Depends on the `realtime` schema,
-- which exists in every Supabase database.

CREATE FUNCTION public.portfolio_changes() RETURNS trigger
    LANGUAGE plpgsql
    AS $$begin
  perform realtime.broadcast_changes(
    'table:' || TG_TABLE_NAME,
    TG_OP,
    TG_OP,
    TG_TABLE_NAME,
    TG_TABLE_SCHEMA,
    NEW,
    OLD
  );
  return null;
end;$$;

-- Triggers -----------------------------------------------------------------

CREATE TRIGGER handle_portfolio_changes
    AFTER INSERT OR DELETE OR UPDATE ON public.portfolio
    FOR EACH ROW EXECUTE FUNCTION public.portfolio_changes();

CREATE TRIGGER handle_portfolio_v2_changes
    AFTER INSERT OR DELETE OR UPDATE ON public.portfolio_v2
    FOR EACH ROW EXECUTE FUNCTION public.portfolio_changes();

-- Row Level Security -------------------------------------------------------

ALTER TABLE public.portfolio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_v2 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all reads" ON public.portfolio
    FOR SELECT USING (true);

CREATE POLICY "Allow all reads" ON public.portfolio_v2
    FOR SELECT USING (true);

-- Grants -------------------------------------------------------------------

GRANT ALL ON TABLE public.portfolio    TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.portfolio_v2 TO anon, authenticated, service_role;
